from pathlib import Path
import environ
import os
from decouple import config

# ========================
# Пути
# ========================
BASE_DIR = Path(__file__).resolve().parent.parent

# ========================
# Подключаем .env
# ========================
env = environ.Env(DEBUG=(bool, False))
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# ========================
# Основные настройки
# ========================
SECRET_KEY = env('SECRET_KEY')
DEBUG = env.bool("DEBUG")
ALLOWED_HOSTS = ["*"]

# ========================
# Email
# ========================
EMAIL_BACKEND = env('EMAIL_BACKEND')
EMAIL_HOST = env('EMAIL_HOST')
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS')
EMAIL_PORT = env.int('EMAIL_PORT')
EMAIL_HOST_USER = env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL')

# ========================
# Database
# ========================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env.int('DB_PORT'),
    }
}

# ========================
# Installed apps
# ========================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Сторонние
    'phonenumber_field',
    'rest_framework',
    'rest_framework.authtoken',
    'drf_yasg',
    'django_filters',
    # Наши приложения
    'accounts',
    'applications',
]

# ========================
# Middleware
# ========================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

# ========================
# Templates
# ========================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# ========================
# Auth
# ========================
AUTH_USER_MODEL = 'accounts.User'

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ========================
# Internationalization
# ========================
LANGUAGE_CODE = 'ru'
TIME_ZONE = 'Asia/Bishkek'
USE_I18N = True
USE_TZ = True

# ========================
# DRF
# ========================
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 12,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend'
    ],
}

# ========================
# Static / Media
# ========================
STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# ========================
# Default primary key
# ========================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ========================
# Celery
# ========================
REDIS_HOST = config('REDIS_HOST', default='127.0.0.1')
REDIS_PORT = config('REDIS_PORT', default=6379, cast=int)

CELERY_BROKER_URL = f'redis://{REDIS_HOST}:{REDIS_PORT}/0'
CELERY_RESULT_BACKEND = f'redis://{REDIS_HOST}:{REDIS_PORT}/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

CELERY_TIMEZONE = 'UTC'
CELERY_ENABLE_UTC = True

















# """
# Django settings for core project.

# Generated by 'django-admin startproject' using Django 4.2.26.

# For more information on this file, see
# https://docs.djangoproject.com/en/4.2/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/4.2/ref/settings/
# """

# from pathlib import Path
# import environ
# import os

# # Build paths inside the project
# BASE_DIR = Path(__file__).resolve().parent.parent

# # ========================
# # 1. Подключаем .env
# # ========================
# env = environ.Env(
#     DEBUG=(bool, False)
# )
# environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# # ========================
# # 2. Основные секреты
# # ========================
# SECRET_KEY = env('SECRET_KEY')
# DEBUG = env.bool("DEBUG")
# ALLOWED_HOSTS = ["*"]

# # ========================
# # 3. Email
# # ========================
# EMAIL_BACKEND = env('EMAIL_BACKEND')
# EMAIL_HOST = env('EMAIL_HOST')
# EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS')
# EMAIL_PORT = env.int('EMAIL_PORT')
# EMAIL_HOST_USER = env('EMAIL_HOST_USER')
# EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
# DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL')

# # ========================
# # 4. Database
# # ========================
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': env('DB_NAME'),
#         'USER': env('DB_USER'),
#         'PASSWORD': env('DB_PASSWORD'),
#         'HOST': env('DB_HOST'),
#         'PORT': env.int('DB_PORT'),
#     }
# }

# # Application definition

# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     'phonenumber_field',
#     'accounts',
#     'applications',
#     'rest_framework',
#     'rest_framework.authtoken',
#     'drf_yasg',
#     'django_filters',
# ]

# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# ]

# ROOT_URLCONF = 'core.urls'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [
#             BASE_DIR / 'templates',
#         ],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = 'core.wsgi.application'


# # Database
# # https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# # DATABASES = {
# #     'default': {
# #         'ENGINE': 'django.db.backends.sqlite3',
# #         'NAME': BASE_DIR / 'db.sqlite3',
# #     }
# # }


# # Password validation
# # https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]

# AUTH_USER_MODEL = 'accounts.User'

# # Internationalization
# # https://docs.djangoproject.com/en/4.2/topics/i18n/

# LANGUAGE_CODE = 'ru'

# TIME_ZONE = 'Asia/Bishkek'

# USE_I18N = True

# USE_TZ = True

# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': [
#         'rest_framework.authentication.BasicAuthentication',
#         'rest_framework.authentication.SessionAuthentication',
#         'rest_framework.authentication.TokenAuthentication',
#     ],

#     'DEFAULT_PAGINATION_CLASS':'rest_framework.pagination.PageNumberPagination',
#     'PAGE_SIZE':12,

#     'DEFAULT_FILTER_BACKENDS':[
#         'django_filters.rest_framework.DjangoFilterBackend'
#     ],
# }



# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/4.2/howto/static-files/

# STATIC_URL = "/static/"

# STATICFILES_DIRS = [
#     BASE_DIR / "static",
# ]

# STATIC_ROOT = BASE_DIR / "staticfiles"

# MEDIA_URL = "/media/"
# MEDIA_ROOT = BASE_DIR / "media"

# # Default primary key field type
# # https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# AUTH_USER_MODEL = 'accounts.User'


# # EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# # EMAIL_HOST = 'smtp.gmail.com'
# # EMAIL_USE_TLS = True
# # EMAIL_PORT = 587

# # # EMAIL_HOST = 'smtp.yandex.com'
# # # EMAIL_USE_SSL = True
# # # EMAIL_PORT = 465


# # EMAIL_HOST_USER = 'emailforbackandskils@gmail.com'
# # EMAIL_HOST_PASSWORD = 'lybdjpfvungctdxy'  

# # DEFAULT_FROM_EMAIL = 'emailforbackandskils@gmail.com'


# # import environ
# # import os

# # env = environ.Env(
# #     DEBUG=(bool, False)
# # )

# # # читаем .env файл
# # environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# # # Основные секреты
# # DEBUG = env.bool("DEBUG")
# # SECRET_KEY = env("SECRET_KEY")

# # # Настройки email
# # EMAIL_BACKEND = env('EMAIL_BACKEND')
# # EMAIL_HOST = env('EMAIL_HOST')
# # EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS')
# # EMAIL_PORT = env.int('EMAIL_PORT')
# # EMAIL_HOST_USER = env('EMAIL_HOST_USER')
# # EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
# # DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL')























# # """
# # Django settings for core project.
# # Generated by 'django-admin startproject' using Django 4.2.26.
# # """

# # from pathlib import Path
# # import environ
# # import os

# # # ========================
# # # Пути
# # # ========================
# # BASE_DIR = Path(__file__).resolve().parent.parent

# # # ========================
# # # Подключаем .env
# # # ========================
# # env = environ.Env(
# #     DEBUG=(bool, False)
# # )
# # environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# # # ========================
# # # Основные секреты
# # # ========================
# # SECRET_KEY = env('SECRET_KEY')
# # DEBUG = env.bool("DEBUG")
# # ALLOWED_HOSTS = ["*"]

# # # ========================
# # # Email
# # # ========================
# # EMAIL_BACKEND = env('EMAIL_BACKEND')
# # EMAIL_HOST = env('EMAIL_HOST')
# # EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS')
# # EMAIL_PORT = env.int('EMAIL_PORT')
# # EMAIL_HOST_USER = env('EMAIL_HOST_USER')
# # EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
# # DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL')

# # # ========================
# # # Database (PostgreSQL)
# # # ========================
# # DATABASES = {
# #     'default': {
# #         'ENGINE': 'django.db.backends.postgresql',
# #         'NAME': env('DB_NAME'),
# #         'USER': env('DB_USER'),
# #         'PASSWORD': env('DB_PASSWORD'),
# #         'HOST': env('DB_HOST'),
# #         'PORT': env.int('DB_PORT'),
# #     }
# # }

# # # ========================
# # # Installed apps
# # # ========================
# # INSTALLED_APPS = [
# #     'django.contrib.admin',
# #     'django.contrib.auth',
# #     'django.contrib.contenttypes',
# #     'django.contrib.sessions',
# #     'django.contrib.messages',
# #     'django.contrib.staticfiles',
# #     'phonenumber_field',
# #     'accounts',
# #     'applications',
# #     'rest_framework',
# #     'rest_framework.authtoken',
# #     'drf_yasg',
# #     'django_filters',
# # ]

# # MIDDLEWARE = [
# #     'django.middleware.security.SecurityMiddleware',
# #     'django.contrib.sessions.middleware.SessionMiddleware',
# #     'django.middleware.common.CommonMiddleware',
# #     'django.middleware.csrf.CsrfViewMiddleware',
# #     'django.contrib.auth.middleware.AuthenticationMiddleware',
# #     'django.contrib.messages.middleware.MessageMiddleware',
# #     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# # ]

# # ROOT_URLCONF = 'core.urls'

# # TEMPLATES = [
# #     {
# #         'BACKEND': 'django.template.backends.django.DjangoTemplates',
# #         'DIRS': [BASE_DIR / 'templates'],
# #         'APP_DIRS': True,
# #         'OPTIONS': {
# #             'context_processors': [
# #                 'django.template.context_processors.debug',
# #                 'django.template.context_processors.request',
# #                 'django.contrib.auth.context_processors.auth',
# #                 'django.contrib.messages.context_processors.messages',
# #             ],
# #         },
# #     },
# # ]

# # WSGI_APPLICATION = 'core.wsgi.application'

# # # ========================
# # # Password validation
# # # ========================
# # AUTH_PASSWORD_VALIDATORS = [
# #     {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
# #     {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
# #     {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
# #     {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
# # ]

# # # ========================
# # # Custom user model
# # # ========================
# # AUTH_USER_MODEL = 'accounts.User'

# # # ========================
# # # Localization
# # # ========================
# # LANGUAGE_CODE = 'ru'
# # TIME_ZONE = 'Asia/Bishkek'
# # USE_I18N = True
# # USE_TZ = True

# # # ========================
# # # DRF
# # # ========================
# # REST_FRAMEWORK = {
# #     'DEFAULT_AUTHENTICATION_CLASSES': [
# #         'rest_framework.authentication.BasicAuthentication',
# #         'rest_framework.authentication.SessionAuthentication',
# #         'rest_framework.authentication.TokenAuthentication',
# #     ],
# #     'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
# #     'PAGE_SIZE': 12,
# #     'DEFAULT_FILTER_BACKENDS': [
# #         'django_filters.rest_framework.DjangoFilterBackend'
# #     ],
# # }

# # # ========================
# # # Static / Media
# # # ========================
# # STATIC_URL = "/static/"
# # STATICFILES_DIRS = [BASE_DIR / "static"]
# # STATIC_ROOT = BASE_DIR / "staticfiles"

# # MEDIA_URL = "/media/"
# # MEDIA_ROOT = BASE_DIR / "media"

# # # ========================
# # # Default primary key
# # # ========================
# # DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'















